ALTER TABLE products
  ADD COLUMN IF NOT EXISTS is_flash_sale TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flash_sale_price DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS flash_sale_end_time DATETIME NULL;
